
version: '3'
services:
    nginx:
        user: nginx:nginx
        build:
            context: nginx
            dockerfile: Dockerfile
        restart: always
        ports:
            - 443:443
    relay:
        build:
            context: nostr-rs-relay
            dockerfile: Dockerfile
        restart: always
        ports:
            - 8080:8080
