
version: '3'
services:
    nginx:
        user: nostr:nostr
        build:
            context: nginx
            dockerfile: Dockerfile
        restart: always
        ports:
            - 443:443
    relay:
        build:
            context: nostr-rs-relay
            dockerfile: Dockerfile
        restart: always
        env_file:
            - .env
        ports:
            - 8080:8080
